<a href="https://colab.research.google.com/github/tanujajeeragal123/get3/blob/main/AILM55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s1=pd.Series([5,10,15,20,25])
print(s1)

0     5
1    10
2    15
3    20
4    25
dtype: int64


In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40,50])
s.index=['a','b','c','d','e']
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
value=s['c']
print(value)

30


In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
s=s+5

a    15
b    25
c    35
d    45
e    55
dtype: int64


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.sum())

10


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.std())

1.118033988749895


In [ ]:
import numpy as np
import random
array = np.random.randint(7,size=(2,2))
print("Input Array: \n",array)
# Smallest element of the x and y axis
print("Smallest number in x axis: ",np.min(array,axis=1))
print("Smallest number in y axis: ",np.min(array,axis=0))


Input Array: 
 [[3 6]
 [5 6]]
Smallest number in x axis:  [3 5]
Smallest number in y axis:  [3 6]


In [ ]:
arr = np.array([1, 2, 3])
print(arr + 2)


[3 4 5]


In [ ]:
def square(number):
     return number*number
nums= [1,2,3,4]
squared_numbers = list(map(square,nums))
print(squared_numbers)
# Using lambda function
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)


[1, 4, 9, 16]
[1, 4, 9, 16, 25, 36]


In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Bangalore']
}
df = pd.DataFrame(data)
print(df)


      Name  Age       City
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore


In [ ]:
import pandas as pd
print(df['Name'])
print(df.loc[0])
print(df.iloc[1])


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Name    Alice
Age        25
City    Delhi
Name: 0, dtype: object
Name       Bob
Age         30
City    Mumbai
Name: 1, dtype: object


In [ ]:
import numpy as np
arr= np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr + arr2)


[2 4 6]


In [ ]:
import pandas as pd
arr = np.array([1, 2, 3])
squared = list(map(lambda x: x**2, arr))
print("Squared using map:", squared)


Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [ ]:
import pandas as pd
def square(number):
        return number*number
nums= [1,2,3,4]
squared_numbers = list(map(square,nums))
print(squared_numbers)
# Using lambda function
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)


[1, 4, 9, 16]
[1, 4, 9, 16, 25, 36]


In [ ]:
import pandas as pd
even = list(filter(lambda x: x % 2 == 0, arr))
print("Even numbers:", even)


Even numbers: [np.int64(2)]


In [ ]:
import numpy as pd
def sum_all(a,b):
      return a+b
nums = [1,2,3,4]
sum = reduce(sum_all,nums)
print(sum)


NameError: name 'reduce' is not defined

In [ ]:
import pandas as pd
print(df['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [ ]:
import pandas as pd
filtered = df[df['Age'] > 25]
print(filtered)


      Name  Age       City
1      Bob   30     Mumbai
2  Charlie   35  Bangalore


In [ ]:
import pandas as pd
df['Salary'] = [50000, 60000, 70000]
df['Age'] = df['Age'] + 1
print(df)


      Name  Age       City  Salary
0    Alice   28      Delhi   50000
1      Bob   33     Mumbai   60000
2  Charlie   38  Bangalore   70000


In [ ]:
import pandas as pd
# list of strings
lst = ['Apple', 'Mango', 'Banana', 'Pine Apple', 'Grapes', 'Watermelon']
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)


            0
0       Apple
1       Mango
2      Banana
3  Pine Apple
4      Grapes
5  Watermelon


In [ ]:
import pandas as pd
# intialise data of lists.
data ={'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]}
# Create DataFrame
df = pd.DataFrame(data)
print(df)


    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000],
    'Age': [25, 30, 28, 32, 40, 38]
}
df = pd.DataFrame(data)
print(df)


  Department Employee  Salary  Age
0         HR    Alice   50000   25
1         HR      Bob   55000   30
2         IT  Charlie   60000   28
3         IT    David   65000   32
4    Finance      Eva   70000   40
5    Finance    Frank   72000   38


In [ ]:
import pandas as pd
result = df.groupby('Department').agg({
    'Salary': 'mean',
    'Age': ['min', 'max']
})
print(result)


             Salary Age    
               mean min max
Department                 
Finance     71000.0  38  40
HR          52500.0  25  30
IT          62500.0  28  32


In [ ]:
import pandas as pd
df=pd.read_csv('/content/exel2.csv')
df.to_csv('output.csv',index=False)
print(df)
df.head()
df.tail()
df.info()


FileNotFoundError: [Errno 2] No such file or directory: '/content/exel2.csv'

In [2]:
import pandas as pd
iris=pd.read_csv('/content/flo.txt')
iris

sepal length\tsepal width\tpetal length\tpetal width\tspecies
0                           5.1\t3.5\t1.4\t0.2\tsetosa           
1                             4.9\t3\t1.4\t0.2\tsetosa           
2                           4.7\t3.2\t1.3\t0.2\tsetosa           
3                           4.6\t3.1\t1.5\t0.2\tsetosa           
4                             5\t3.6\t1.4\t0.2\tsetosa           
..                                                 ...           
145                        6.7\t3\t5.2\t2.3\tvirginica           
146                        6.3\t2.5\t5\t1.9\tvirginica           
147                          6.5\t3\t5.2\t2\tvirginica           
148                      6.2\t3.4\t5.4\t2.3\tvirginica           
149                        5.9\t3\t5.1\t1.8\tvirginica           

[150 rows x 1 columns]